import { StatusBadge } from '@/components/ui'
import { ResourceList } from '@/components/resource-list'
import { RowLink } from '@/components/ui/table'
import { formatDate, formatSelection } from '@/lib/format'
import { toOdooOrder } from '@/lib/list-query'
import { classOptions, subjectOptions, termOptions } from '@/lib/odoo/filter-options'
import { listAssessments } from '@/lib/odoo/models/assessment'
import { selectionOptions } from '@/lib/odoo/selections'
import { m2oLabel } from '@/lib/odoo/types'

export const metadata = { title: 'Assessments · Async School' }

export default async function AssessmentsPage({ searchParams }: PageProps<'/assessments'>) {
  const [states, types, classes, subjects, terms] = await Promise.all([
    selectionOptions('school.assessment', 'state'),
    selectionOptions('school.assessment', 'assessment_type'),
    classOptions(),
    subjectOptions(),
    termOptions(),
  ])

  return (
    <ResourceList
      title="Assessments"
      icon="assessments"
      basePath="/assessments"
      searchParams={searchParams}
      subtitle="Mark lists are generated by Odoo from subject enrolments — never typed in by hand."
      search={{ placeholder: 'Assessment name' }}
      filters={[
        { key: 'status', label: 'Status', options: states },
        { key: 'type', label: 'Type', options: types },
        { key: 'class', label: 'Class', options: classes },
        { key: 'subject', label: 'Subject', options: subjects },
        { key: 'term', label: 'Term', options: terms },
      ]}
      defaultSort={{ field: 'date', direction: 'desc' }}
      load={(query) =>
        listAssessments({
          search: query.search,
          filters: query.filters,
          order: toOdooOrder(query),
          limit: query.limit,
          offset: query.offset,
        })
      }
      rowHref={(row) => `/assessments/${row.id}`}
      emptyTitle="No assessments visible"
      emptyHint="A teacher sees assessments for their own exact assignment only."
      columns={[
        {
          key: 'name',
          label: 'Assessment',
          sortField: 'name',
          render: (row) => <RowLink href={`/assessments/${row.id}`}>{row.name}</RowLink>,
        },
        {
          key: 'type',
          label: 'Type',
          hideBelow: 'lg',
          render: (row) => formatSelection(row.assessment_type),
        },
        { key: 'class', label: 'Class', render: (row) => m2oLabel(row.class_id) },
        { key: 'subject', label: 'Subject', render: (row) => m2oLabel(row.subject_id) },
        { key: 'term', label: 'Term', hideBelow: 'md', render: (row) => m2oLabel(row.term_id) },
        {
          key: 'date',
          label: 'Date',
          sortField: 'date',
          hideBelow: 'sm',
          render: (row) => formatDate(row.date),
        },
        {
          key: 'marks',
          label: 'Marks',
          numeric: true,
          render: (row) => (
            <span title={`out of ${row.max_mark}`}>
              {row.mark_count}
            </span>
          ),
        },
        { key: 'state', label: 'Status', render: (row) => <StatusBadge state={row.state} /> },
      ]}
    />
  )
}
