# -*- coding: utf-8 -*-

#from . import models
from . import school_academic_year
from . import school_term
from . import school_class
from . import school_enrollment
from . import school_enrollment_transfer
from . import school_grade_subject
from . import school_student_subject
from . import school_student
from . import school_student_guardian
from . import school_staff
from . import school_attendance
from . import school_assessment
from . import school_mark
from . import school_result
from . import school_report_card
from . import school_subject
from . import school_teacher
from . import school_teacher_assignment
from . import school_room
from . import school_responsibility
from . import school_program
from . import school_class_schedule
from . import school_announcement
from . import school_documents
from . import res_users
from . import school_teacher_links
from . import school_dashboard
